using Microsoft.EntityFrameworkCore;
using EfCoreLibraryApp.DatabaseFirstModels;

namespace EfCoreLibraryApp.Data
{
    // Simulates a Database First context (as if scaffolded from an existing database).
    // In production, this would be generated by:
    // dotnet ef dbcontext scaffold "ConnectionString" Microsoft.EntityFrameworkCore.SqlServer
    public class DbFirstLibraryContext : DbContext
    {
        public DbFirstLibraryContext(DbContextOptions<DbFirstLibraryContext> options) : base(options) { }

        public DbSet<DbFirstBook> DbFirstBooks { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DbFirstBook>(entity =>
            {
                entity.HasKey(b => b.BookID);
                entity.Property(b => b.Title).IsRequired().HasMaxLength(200);
                entity.Property(b => b.ISBN).HasMaxLength(20);
                entity.Property(b => b.Price).HasColumnType("decimal(10,2)");
            });

            // Seed data for the database first section
            modelBuilder.Entity<DbFirstBook>().HasData(
                new DbFirstBook { BookID = 1, Title = "The Great Gatsby", ISBN = "978-0743273565", PublishYear = 1925, Price = 12.99m },
                new DbFirstBook { BookID = 2, Title = "Moby Dick", ISBN = "978-1503280786", PublishYear = 1851, Price = 9.99m },
                new DbFirstBook { BookID = 3, Title = "Pride and Prejudice", ISBN = "978-1503290563", PublishYear = 1813, Price = 7.99m }
            );
        }
    }
}
